### ISSUE TITLE
Wiki instructions

### ISSUE THREAD

**Issue by twanito** [chriswmackey/Dragonfly#10]
Any chance the install instructions could be in the wiki? I was showing a colleague how to install and it took us forever to find it in the resources folder :)

**Comment by chriswmackey** [comment]
@twanito ,
Very good idea and thanks for posting it.  I just added the install instructions here:
https://github.com/chriswmackey/Dragonfly/wiki/Instructions-for-Installing-Dragonfly
-Chris
