### ISSUE TITLE
Typo in Input parameter for night boundary layer height. 

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#11]
As seen here: http://www.grasshopper3d.com/group/ladybug/forum/topics/dragongfly-boundary-layer-parametrization

The input for the Dragonfly_Boundary_Layer_Parameters says 800m which is causing confusion and leading to too large heights to be set for the night boundary layer height. Change to 80m.

Also as work progresses on UWG_Python and translation efforts on the RSMDef.m  and UWG.m proceed, this might be a good error test to understand if we need to put upper/lower bounds on inputs, and better warning/error messages.

**Comment by chriswmackey** [comment]
Thanks @saeranv .  This is all fixed in the newest version so I am going to close out this issue.
