### ISSUE TITLE
UWG.zip Contains Wrong Directory Name (META vs .META)

### ISSUE THREAD

**Issue by ajakubiec** [chriswmackey/Dragonfly#14]
Hi Chris,

I'm noting an issue I found in the installation of the UWG. The UWGEngine executable looks for files in .\UWG\UWGEngine_mcr\\**.META**\\; however, the directory in UWG.zip is named .\UWG\UWGEngine_mcr\\**META\\** (missing the dot). It needs to be manually renamed using the command prompt's Rename command or a non-Windows Explorer tool to fix this. You might want to automate this for users.

Best,
Alstan

**Comment by TheodoreGalanos** [comment]
I saw this as well yesterday and forgot to mention. I think it might be related to [this](https://github.com/hansukyang/UWG_Matlab/commit/3f1ca09ce27a1056fab91cfa8130c3128bc85f2f)?

You can also fix it by renaming the folder to .META.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
@ajakubiec ,
Thank you for letting me know about this.  I currently try to automate this using this line in Dragonfly_Dragonfly:
https://github.com/chriswmackey/Dragonfly/blob/master/src/Dragonfly_Dragonfly.py#L1000
It also automates the download of the UWG from the UWG_Matlab github.  If you installed the UWG in the Ladybug folder manually, then this automatic renaming won't happen on your system.  Do you think this is what is happening here?  If so, I would recommend deleting the C:/ladybug/UWG folder and re-running Dragonfly_Dragonfly.

**Comment by ajakubiec** [comment]
For me the Ladybug path is in c:\Users\username\AppData\Roaming\Ladybug\, so that hard coded path may not be effective.

**Comment by chriswmackey** [comment]
@ajakubiec ,

Got it. Thanks for finding this issue.  I forgot to make that piece of the code adaptable for people who don't have permissions to run things out of the C:\ drive.

I just pushed a change to the code that should fix this issue:
https://github.com/chriswmackey/Dragonfly/commit/3ab5f7553987a1da31622ad88cb2b6ebca716f4d

Let me know if you get the chance to test it out and thanks again for finding this.
Cheers!
-Chris
