### ISSUE TITLE
error Dragonfly_AMY from NCDC Data component

### ISSUE THREAD

**Issue by hamedsangin** [chriswmackey/Dragonfly#15]
![image](https://user-images.githubusercontent.com/34301946/36355632-8cc499e8-14fb-11e8-90bc-81be23bea05d.png)
Dragonfly_AMY from NCDC Data component error
i download data from https://gis.ncdc.noaa.gov/maps/ncei/cdo/hourly for one year and i had this error !!

**Comment by chriswmackey** [comment]
@hamedsangin ,
Sorry for such a late response. Can you post the year's worth of text data that you input to the component?  This will help me debug the situation.  I am also thinking of writing a new version of this component that uses the [DarkSky API](https://darksky.net/dev) and is more reliable.

**Comment by chriswmackey** [comment]
@hamedsangin ,
I have come to realize with time that the NCDC data set is really messy and it's very hard to write a script that will work for all data that is up there.  As such, I am planning to replace this component with one that uses the [DarkSky API](https://darksky.net/dev).  The developers of Dark Sky have doe a good job cleaning up a lot of this publicly available data and, using what they have built, I can make something much more reliable.  The only thing is that, if someone wants to generate more than 3 epws in a day, they will have to pay DarkSky a few cents for each epw they generate after that.  However, I think that it is worth it given how reliable their API seems to be.  For now, I am going to close out this issue and just say that the NCDC component is deprecated.
