### ISSUE TITLE
dragonfly run problem

### ISSUE THREAD

**Issue by hamedsangin** [chriswmackey/Dragonfly#17]
hi dear chris
![image](https://user-images.githubusercontent.com/34301946/39590167-6152adbe-4f15-11e8-981a-697cf9449e02.png)
i follow Instructions install ccweathergen and dragon fly but i got still this massage error
i do the fallowing error but still problem not solved
rhino 6 grasshoper v1 win 10

**Comment by chriswmackey** [comment]
@hamedsangin ,
You have to follow these instructions for the Matlab compiler if you want to run the UWG workflows and get rid of those wanting messgaes:

https://github.com/chriswmackey/Dragonfly/blob/master/resources/Installation_Instructions.MD

**Comment by hamedsangin** [comment]
@chriswmackey 
UWG must copy in C:\ladybug
instead C:\
that didn't mention in is this address
https://github.com/chriswmackey/Dragonfly/blob/master/resources/Installation_Instructions.MD
tnk U chris :)

**Comment by chriswmackey** [comment]
Good point.  The download is supposed to happen automatically in the background but I should add that in case the automatic download fails.
We're pretty close to pushing out a new version of Dragonfly that will use the python version of the UWG.  After we finish that, the installation process is going to get a lot easier.
