### ISSUE TITLE
Component to Make DF Typology from Building Footprints

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/Dragonfly#21]
While only some urban areas have fully-detailed 3D models available, nearly all have some sort of 2D representation as polygons.

Because the new dragonfly API is fully object-oriented, I just need to add a fromPolygons() method to the building typology class to have this capability available.

**Comment by saeranv** [comment]
@chriswmackey yes! This would be so awesome with GIS data.

**Comment by chriswmackey** [comment]
Your wish is granted @saeranv !

This has been addressed via:
https://github.com/chriswmackey/Dragonfly/commit/7030567fc279e92bfef668d6b3e1bfa5e3da2420

You can also see how much cleaner the workflow is in the second sample file here:
https://github.com/chriswmackey/Dragonfly/tree/master/sampleFiles

Now that I've put it together, I actually envision most people using this workflow in Dragonfly since it's much faster and cleaner.  The method with closed solids really only seems best suited to downtown areas with large buildings and unique geometries.
