### ISSUE TITLE
PEP8-ify the Core Libraries

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/Dragonfly#26]
I can get away with not doing this before the first release.  It just has to be done some time before I pull everything out into standalone .py files that will go under the Ladybug Tools organization.

**Comment by saeranv** [comment]
Is there a tool you're using to find and suggest fixes for style inconsistencies like this? I've heard of pylint and linters to do this, but haven't used it...

**Comment by chriswmackey** [comment]
@saeranv ,
When I translate the core libraries to just be .py files, I will be using the Atom text editor and I have Atom outfitted with a number of plugins to do PE8 checking for me including the following:
![image](https://user-images.githubusercontent.com/5567574/41201299-3ce91cac-6c83-11e8-832a-7dc9162ea2a3.png)
![image](https://user-images.githubusercontent.com/5567574/41201303-49c45996-6c83-11e8-94b4-102a28383642.png)

Pretty much all of them are for doing PEP8 checking except the script and autocomplete one.

In addition to this, there are a few PEP8 standards that just can't be checked with a linter and you just need to follow them.  One of them is that camelCase is no longer allowed in PEP8 and variables are supposed to be written with underscores_between_words.  For these cases, I would say you should take a quick read over the Google python style guide here:
https://google.github.io/styleguide/pyguide.html

**Comment by saeranv** [comment]
Cool, I downloaded the more popular pep8 linting libraries there. I've been meaning to try and follow pep8 rigorously for a while, but just have never really got around to it.

**Comment by chriswmackey** [comment]
I am closing out this specific issue now that the dragonfly[+] libraries have been PEP8-ified.  I think it's still a good idea to PEP8-ify the UWG at some point, @saeranv .
