### ISSUE TITLE
Installing Dragonfly with Rhino 6

### ISSUE THREAD

**Issue by annasong20** [chriswmackey/Dragonfly#33]
Hi,

I have Rhino 6, and I was trying to install Dragonfly following instructions from this link: https://github.com/chriswmackey/Dragonfly/wiki. To install Ladybug, I followed the link on the previous site to the following link: https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Installation_Instructions.md. The third step is to install GHPython 0.6.0.3 using the following link: http://www.food4rhino.com/app/ghpython.

I downloaded the file using the download button in the first row. However, after dragging the file titled ghpython2 onto the Grasshopper canvas opened in Rhino6, I get the error depicted in the picture below. I found that GHPython.gha is a file that comes with Grasshopper, which comes with the installation of Rhino 6.

![img-20180615-wa0011](https://user-images.githubusercontent.com/40309066/41494753-2cb920ae-70e6-11e8-976c-399d4507f51c.jpeg)

I'm relatively new to Rhino and Ladybug Tools. Sorry if there is something obvious that I'm missing.
 Thanks so much!

**Comment by chriswmackey** [comment]
@annasong20 ,
GHPython comes installed automatically in Rhino 6 (as does grasshopper). So you should not do this whenever you install Ladybug on Rhino 6.  We should change the install instructions over on the Ladybug github to be clear that the Grasshopper and Python installations only need to be done when using Rhino 5.  Also, in the future, questions like this should be posted to our forum:
https://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8

Only things that are explicitly bugs or features should be posted to the github.
