### ISSUE TITLE
Update Dragonfly to Assign all Building Parameters After Reading All Input

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/Dragonfly#34]
At the moment, some of the critical facade parameters are being overwritten when the inputs are being read in.

**Comment by saeranv** [comment]
I've pulled out the initialization of the list of BEM objects into its own method. So you should just be able to use your own Dragonfly method now. 

Details here: https://github.com/ladybug-tools/urbanWeatherGen/issues/62

**Comment by chriswmackey** [comment]
Great! Thank you @saeranv !

**Comment by chriswmackey** [comment]
This has been addressed via
https://github.com/chriswmackey/Dragonfly/commit/86a3b22cdd0c0dd24a0c0ebc5191ae00e435a2ce
