### ISSUE TITLE
old version of Dragonfly didn't remove

### ISSUE THREAD

**Issue by hamedsangin** [chriswmackey/Dragonfly#37]
![image](https://user-images.githubusercontent.com/34301946/42460724-d8d0d316-83b3-11e8-83cd-897ff59edd26.png)
after update the old version didn't remove as see in pic

**Comment by hamedsangin** [comment]
maybe its because of new name for component, it happen

**Comment by chriswmackey** [comment]
@hamedsangin ,
Given that the first official release of Dragonfly was just today, there isn't any compatability with the previous Dragonfly versions (including the previous update vomponents and workflows). So you have to remove the old components manually from the user objects folder.

**Comment by chriswmackey** [comment]
I am going to close this issue out.  Feel free to reopen if my previous response did not address the issue.
