### ISSUE TITLE
Potential bug re: area-weighted SHGC value

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#41]
From @annasong20 here: https://discourse.ladybug.tools/t/dragonfly-ladybug-potential-bugs-and-question/3265/17, we may not be area-weighting the SHGC values when inputted by the user. I'm looking into this now, and hopefully an send a PR soon.

**Comment by chriswmackey** [comment]
I'm closing out this issue now that it has been fixed via https://github.com/chriswmackey/Dragonfly/commit/46789dc0a96c3afe91cba0bee4d24222e65d68a8
