### ISSUE TITLE
Characteristic Length Discrepancy re: radius, diameter or square edge.

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#43]
Re: the 2nd question from @annasong20 here: https://discourse.ladybug.tools/t/dragonfly-ladybug-potential-bugs-and-question/3265/21?u=saeranvasanthakumar

> Instances of both the City and Terrain classes have the attribute characteristic_length. When a City object is created, its characteristic_length attribute is the same as its Terrain object’s characteristic_length attribute.
> In the Terrain class’s area attribute’s setter method, characteristic_length is calculated as follows

> self._characteristic_length = math.sqrt(self._area)
> In this case, characteristic_length is the length of one side of a square with the same area as the actual terrain. However, in the City class’s building_typologies and update_geo_from_typologies methods, the site area is recovered by assuming that the characteristic_length is the radius of a circle that has area matching the terrain area.

> site_area = math.pow(self.characteristic_length,2) * math.pi
> Does this mean that when calculating characteristic_length in the Terrain class, the terrain area should be divided by pi before the square root is taken?

In the UWG code characteristic length is the edge of a square encompassing the urban area. This is what the UWG assumes when it calculates total urban area, built area etc, i.e here: https://github.com/hansukyang/UWG_Matlab/blob/master/UBLDef.m#L28

However, I just downloaded, and ctrl-F-ed my way through Michael Street's thesis, which @chris references for this 500m radius value, and it does look like Street is using a radius value, of around 500m for charLength.

More discrepancies:
- Nakano specifies this value as the city _diameter_ of 1000m.
- Jiachen specifies this value as 1000m, but is not clear if it is a diameter/radius/square length.
- The original initialize.m file from the UWG_Matlab is defined as 1000m, and is not clear if it is a diameter/radius/square length.

@chriswmackey , any idea of why there is this seeming discrepancy between the UWG code (assumes charLength = square edge at 1000m), and Street's thesis (assumes charLength = radius of circle at 500m)? 

S

**Comment by saeranv** [comment]
Also note, we've had this discussion before: https://github.com/ladybug-tools/uwg/issues/18

**Comment by chriswmackey** [comment]
@saeranv ,
Thanks for digging into this and it's no wonder why I was surprised when I saw that the UWG code is treating the characteristic length as the length of a square (you are right that everyone else seems to call it a radius). Given that we can clearly see that the code is written using the side of a square, I think that I should make sure Dragonfly always treats the length as the side of a square for now. However, it's possible that this parameters is something that changed in the Matlab UWG over time and this might be the source of the confustion. @hansukyang might have some more I sight into this.

**Comment by hansukyang** [comment]
I think this was always defined as a side of a square and there shouldn't
have been any change from Bruno's version. I remember trying a range of
this value and not seeing big impact from this and understood it mostly as
a way to define an area where average urban landscape features are
extracted from.

**Comment by chriswmackey** [comment]
It seems that the confusion here was just a mismatch between [what was stated in the original UWG documentation](http://urbanmicroclimate.scripts.mit.edu/uwg_parameters.php) and what was actually the case under the hood in the UWG.  This has been fixed (both in terms of implementation and documentation) for both the plugin here:
https://github.com/chriswmackey/Dragonfly/commit/9df144431e1c1003ea693d750a6227564bd50c62
As well as the dragonfly core libraries that I have been working on:
https://github.com/ladybug-tools/dragonfly/commit/06ded858589c3253cb00af61d6407e096eba7e26
So I am closing this issue out.
