### ISSUE TITLE
BldgTypology component error.

### ISSUE THREAD

**Issue by paulleondrake** [chriswmackey/Dragonfly#44]
Certain Breps, or possibly combinations of Breps, is failing with the following error. This appears to a be a similar error to past Ladybug tools. Can anyone explain situations they have had this happen?

{0;0}
0. Runtime error (ArgumentTypeException): Multiple targets could match: Compute(Surface), Compute(IEnumerable[GeometryBase]), Compute(Brep), Compute(Curve), Compute(Hatch), Compute(Mesh)

Traceback:
  line 451, in getFloorBreps, "<string>"
  line 644, in calculateTypologyGeoParams, "<string>"
  line 1061, in from_geometry, "<string>"
  line 71, in script

I can narrow the issue down to only occurring at specific breps, but am not certain what about the breps are causing the issue. 

_Originally posted by @paulleondrake in https://github.com/chriswmackey/Dragonfly/issues/1#issuecomment-427388221_

**Comment by chriswmackey** [comment]
@paulleondrake ,

Sorry for the late response.  Can you post a Rhino and Grasshopper definition that recreates the issue.
Also can you confirm which Service Release of Rhino 6 you are using?  The error that you are getting is one that comes from Rhinocommon so it seems the issue is either with your geometry or the version of Rhino that you are using.

**Comment by paulleondrake** [comment]
@chriswmackey Thank you for the response anyhow. I attached a definition showing a number of breps out of a collection that are causing this issue. This set in particular has a number of the breps, which if included at all, fail the typology component. Sometimes, generating a different area of the city yields no issues at all, whereas other times it seems having only one problematic geometry instance fails everything. We can cull out that geometry, somewhat defeating the purpose though. 

I'm currently using Rhino 6 SR9 build 6.9.18271.20591 (and other workstations that have updated differently - i.e. my computer at home is on a version of 6.10)

[Dragonfly BLDGTYPO Issue.zip](https://github.com/chriswmackey/Dragonfly/files/2543813/Dragonfly.BLDGTYPO.Issue.zip)

**Comment by chriswmackey** [comment]
@paulleondrake ,
Thanks for reporting this.  It seemed like this was just a result of the Rhino intersection methods failing in cases where it should be ignored.  This change fixes the issue:
https://github.com/chriswmackey/Dragonfly/commit/c471ddadd878054760a609067015a3a9dda51876

Update your components and you should be good to go (though I would still recommend doing some cleanup on your geometry as you have a lot of overlapping building solids that can change the accuracy of the uwg.
