### ISSUE TITLE
Name of epw file

### ISSUE THREAD

**Issue by frank984** [chriswmackey/Dragonfly#5]
As reported [here](http://www.grasshopper3d.com/group/ladybug/forum/topics/dragonfly-issue?commentId=2985220%3AComment%3A1597286&xg_source=msg_com_gr_forum) there is a mistake with the name of .epw file. See the link above for more details.

**Comment by chriswmackey** [comment]
@frank984 ,
I have fixed this since you posted it.  Sorry for the incredibly late response
