### ISSUE TITLE
error running install.gh

### ISSUE THREAD

**Issue by isabelauer** [chriswmackey/Dragonfly#55]
Hello,

unfortunately I have troubles running the install.gh file. I followed the instructions regarding ladybug/honeybee and dragonfly installation but -apparently- the copying from the userobjects to C:\users\zentr\AppData\Roaming\Grasshopper\UserObjects does not work.

This error message appears: Runtime error (ArgumentOutOfRangeException): Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index

(Index was out of range. Must be non-negative and less than the size of the collection. parametername:index)

![error_install_dragonfly](https://user-images.githubusercontent.com/26246512/52789205-8010f000-3063-11e9-9672-bd68dea60680.JPG)

However, looking into the folder C:\users\zentr\AppData\Roaming\Grasshopper\UserObjects there is a new folder Dragonfly which contains the following 20 userobjects

![userobjects](https://user-images.githubusercontent.com/26246512/52789505-48ef0e80-3064-11e9-8c50-71f7d17a0fc1.jpg)

Any suggestions/ ideas how to solve this problem?

Thanks very much in advance!

Isabel

**Comment by sytsek47** [comment]
Dear Dragonfly-developers/users,

I am running exactly into the same issue, which I am not able to resolve. Can anyone please help me/us? It makes the work much easier to build real-world envimet simulations.

Many thanks in advance,
kind regards,
Sytse

![installergh](https://user-images.githubusercontent.com/25325023/58009591-133c4480-7aef-11e9-93cb-3928da8802ee.png)

**Comment by chriswmackey** [comment]
@isabelauer and @sytsek47 ,

Sorry for the late reply here. It looks like this issue may result from having g an older version of some of the components installed. Can you try completely deleting the Dragonfly folder and seeing if you can re-run the installation file without issues. I'll see if I can check the exact line that is failing later.

**Comment by sytsek47** [comment]
Dear Chris,

Thank you for your reply. I was able to get the envimet utilities by moving the DragonFlyEnvimet.gha to the Components file in the Grasshopper Plugins folder. C:\Program Files\Rhino 6\Plug-ins\Grasshopper\Components.

Kind regards,
Sytse

**Comment by sytsek47** [comment]
I was able to get the envimet utilities by moving the DragonFlyEnvimet.gha to the Components file in the Grasshopper Plugins folder. C:\Program Files\Rhino 6\Plug-ins\Grasshopper\Components. I got this idea from a discussion how to install custom ghx compontents: https://www.grasshopper3d.com/forum/topics/how-do-i-install-a-custom-ghx

**Comment by yingz123** [comment]
Hi, I have got the same problem not being able to get the envimet features. I tried to delete all the old files and even reinstall rhino, but it still doesnt work. It would be great if you could provide a solution.

**Comment by AntonelloDN** [comment]
Hi @yingz123,
Could you please provide screenshots about your UserObjects folder and Components folder?
Thanks

**Comment by yuenyat** [comment]
Hi @AntonelloDN 
I got same problem and have tried to reinstall rhino as well.
Here are my screenshots. Wish they help.

![image](https://user-images.githubusercontent.com/30655212/70746093-36b32f00-1d60-11ea-8d3e-9712eda3a13f.png)
![image](https://user-images.githubusercontent.com/30655212/70746453-cf49af00-1d60-11ea-9908-a5b41fb2b4d4.png)
![image](https://user-images.githubusercontent.com/30655212/70746659-2cddfb80-1d61-11ea-8f8a-f9bea3b2e304.png)
