### ISSUE TITLE
some problems about the output interval

### ISSUE THREAD

**Issue by yuanyimei** [chriswmackey/Dragonfly#56]
Dear chris @chriswmackey
I just wondering how to set the  the output interval in the dragonfly workflow.As we can see in the old ladybug version（VER0.0.65）the output interval can be set. But I can't find the option in the dragonfly workflow.So how can I set this in the dragonfly?Looking forward to your reply.
![_20190305112505](https://user-images.githubusercontent.com/39336329/53779049-c4443180-3f39-11e9-92cb-06146ae1554e.png)
![_20190305112459](https://user-images.githubusercontent.com/39336329/53778962-7e876900-3f39-11e9-8acd-d47454bf68c1.png)

**Comment by AntonelloDN** [comment]
Hi @yuanyimei,

I am in charge of the part of envimet components for Grasshopper.
The old component was made following a text form whilst the new one follow the XML structure which is used in latest version of ENVI_MET. OutputTiming is not part of the main settings anymore.

I can create a new component today and add it to settings component. I suggest you look at "DF Envimet Information" where I post a comment when new components are available.

Regards,
Antonello

**Comment by yuanyimei** [comment]
Hi  @AntonelloDN,

It works! I 'm so excited, thank you for your kindly help.

yuanyimei

**Comment by AntonelloDN** [comment]
Solved by #57 
Thanks @yuanyimei
