### ISSUE TITLE
problems zbottom buildings dragonfly

### ISSUE THREAD

**Issue by isabelauer** [chriswmackey/Dragonfly#59]
Hi,

EDIT: It seems, that the problem only occurs if I change the input for telescope/ starttelescopeheight.

I am having problems converting closed polysurfaces in Rhino to buildings in ENVImet Spaces.

After running my .gh file, a Spaces File is created. However, in ENVImet it shows that z bottom of the buildings z0=2m (and it should be z0=0m). 
I am not using any topography information.
The preview of the Grid in Rhino shows already the problem: the red markers are not on the ground/ the level where the buildings & soil area are located. 
![screenshot_rhino](https://user-images.githubusercontent.com/26246512/60432305-3a178b80-9c02-11e9-98d7-9080cb1bae44.JPG)

Have you already experienced this effect?

Thanks in advance.
Isabel

**Comment by AntonelloDN** [comment]
grid points consist of centroids
