### ISSUE TITLE
start envimet simulation without opening envi-met software

### ISSUE THREAD

**Issue by lisha992610** [chriswmackey/Dragonfly#61]
Hello

According to the article: https://www.envi-met.com/first-envi-met-plugin-for-rhino-grasshopper/ .
I read on the above article, that this plugin could convert 3d model (e.g. .3ds) into envi-met model area (.inx) and run the envi-met simulation without opening the software. Is that correct?

I am attempting to put envi-met simulation on supercomputers where we don't have any user interface. Part as automation to simplify multiple simulation using different scenario (3d models).

I would like to ask different opinion if this idea is feasible. Open and appreciate for different opinion. Thank you very much.

**Comment by AntonelloDN** [comment]
Hi @lisha992610,
Yes, you can but with some restrictions. Building have to be closed volumes, and you need to clean geometries as much as possible. I have made a new version of plugin and it is already available in beta version on my github page. I have improved usability of it. I will send a pull request to Dragonfly soon.

As you should know, Envimet software is mainly for PC for now. Keep in mind this for your supercomputer. Go directly with Windows is the best way for me.

You can run envimet as console application, so without an user interface. And you can theorically connect your local machine where your files are to supercomputer and you could run simulation directly to it (you can point the right path in a *.bat file).
I will continue to investigate your case. In the meentime, You can start from these advices

I am really courios about this experiment, I would like to assist you in free time.

Antonello

**Comment by AntonelloDN** [comment]
Hi @lisha992610,

both INX and SIMX should be saved on supercomputer. Have you had a test?

Antonello

**Comment by AntonelloDN** [comment]
@lisha992610, I close this issue because of inactivity. If you would like you can open it again. Thanks for collaboration.
