### ISSUE TITLE
There are not Naked edge but it's not solid or closed polysrf

### ISSUE THREAD

**Issue by spark9504** [chriswmackey/Dragonfly#63]
Hi,

I am trying to use Envi-met with dragonfly and having hard time with "DF Envimet Buildings" function.
![image](https://user-images.githubusercontent.com/56981582/68553951-915b2180-0468-11ea-9e45-671a55cea694.png)

My buildings do not have Naked edges but, as you can see, it keeps saying "1. Please provide closed geometries" 

![image](https://user-images.githubusercontent.com/56981582/68554034-0b8ba600-0469-11ea-8d10-e5cbb2383131.png)

this is an object description of my building, and it says "closed solid with 14 surfaces"
Please help me!!

**Comment by AntonelloDN** [comment]
Hi @spark9504,

Can you subscribe [https://discourse.ladybug.tools/](url) and open a discussion there?
I need to check your file in order to help you.

Antonello
