### ISSUE TITLE
Roof and Wall Veg Fraction

### ISSUE THREAD

**Issue by twanito** [chriswmackey/Dragonfly#7]
Input mentions value from 0 to 1 to input fraction of vegetation on surface but code checks for value between 1 and 8.

Error output:"VegFraction must be between 1 (warmest) and 8 (coldest)"

Worth either correcting input requirements or input hint (whichever is incorrect).

Look forward to beta testing this further! :)

**Comment by chriswmackey** [comment]
Sorry for the very late response, @twanito .
Hmmm. I didn't realize that the UWG supported Veg Fractions like this.  Let me give it a try on my end.

**Comment by chriswmackey** [comment]
@twanito ,
Yes, this was a bug in my check function.  It is fixed now:
https://github.com/chriswmackey/Dragonfly/commit/93e90174975337b89a6a037f2ba05b60a4e170b9
-Chris

**Comment by twanito** [comment]
Nice one thanks! Good luck with the PerformanceNetwork presentation this afternoon.
