### ISSUE TITLE
Problem of envimet location 

### ISSUE THREAD

**Issue by Bowen49** [chriswmackey/Dragonfly#82]
Hello, 

I am trying to follow the same steps as the ones in the tutorials of Envi-met for creating an INX file.

So the task at hand is, I have several Rhino files which are actually the 3d models of a built area. I would like to convert that file into an INX file and eventually
recreate the same structures inside Envi-met. However, at the start of the procedure, when I use the "DFEnvimetlocation" component I get the error:

"1. Solution exception:Input string was not in a correct format."

What could I be doing wrong?

Sorry for the inconvenience. I am new at both Rhino/Grasshopper and Envi_met. :?

Thanks for any help!!

P.S.: I am attaching a screenshot of the steps

![Capture](https://user-images.githubusercontent.com/108074979/175319786-a9829e13-6532-45c5-9434-3dd174ef0230.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi @Bowen49 you should post this question to the forum: https://discourse.ladybug.tools

The answer probably is that you need to use the location component from the legacy plugins.
